services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    volumes:
      - ./uptime-kuma-data:/app/data
      - ${PODMAN_SOCKET}:/var/run/docker.sock:ro
    security_opt:
      - label=disable
    logging:
      driver: journald
