services:
  syncthing:
    image: docker.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - STGUIADDRESS=0.0.0.0:${SYNCTHING_UI_PORT:-8384}
    volumes:
      - ./syncthing/config:/config:Z
      - ${SYNCTHING_DATA_PATH}:/var/sync:Z
    ports:
      - "${SYNCTHING_UI_PORT:-8384}:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: always
    tmpfs:
      - /tmp:size=50M
      - /run:size=50M
    logging:
      driver: journald

  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    security_opt:
      - label=disable
    ports:
      - "${FILEBROWSER_PORT:-3670}:8080"
    group_add:
      - keep-groups
    environment:
      - TZ=${TZ}
    command: ["--database", "/config/filebrowser.db", "--root", "/srv", "--address", "0.0.0.0", "--port", "8080"]
    healthcheck:
      test: ["CMD-SHELL", "filebrowser version"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ${FILEBROWSER_ROOT}:/srv:rw
      - ./filebrowser:/config:rw
    logging:
      driver: journald

  kavita:
    image: docker.io/jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "${KAVITA_PORT:-5000}:5000"
    volumes:
      - ${KAVITA_CALIBRE_PATH}:/srv/Calibre:rw
      - ${KAVITA_COMIC_PATH}:/srv/Comic:rw
      - ${KAVITA_MANGA_PATH}:/srv/Manga:rw
      - ./kavita:/kavita/config:Z
    logging:
      driver: journald
