services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "0:0"
    privileged: true
    restart: always
    security_opt:
      - label=disable
    ports:
      - "3670:80"
    environment:
      - TZ=${TIMEZONE}
    command: ["--database", "/config/filebrowser.db", "--root", "/srv", "--address", "0.0.0.0"]
    volumes:
      - ${NAS_ROOT_PATH}:/srv:z
      - ./filebrowser:/config:z
    logging:
      driver: journald

  syncthing:
    image: docker.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ./syncthing/config:/config:Z
      - ${SYNCTHING_PATH}:/var/sync:Z
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
    restart: always
    tmpfs:
      - /tmp:size=50M
      - /run:size=50M
    logging:
      driver: journald

  kavita:
    image: docker.io/jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "5000:5000"
    volumes:
      - ${KAVITA_PATH}/Calibre/:/srv/Calibre:rw
      - ${KAVITA_PATH}/Comic:/srv/Comic:rw
      - ${KAVITA_PATH}/Manga/:/srv/Manga:rw
      - ./kavita:/kavita/config:Z
    logging:
      driver: journald
