services:
  homepage:
    image: docker.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./homepage/images:/app/public/images:Z
      - ./homepage/config:/app/config:Z
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TIMEZONE}
      - HOMEPAGE_VAR_SERVER_HOST_VALIDATION=false
      - HOMEPAGE_ALLOWED_HOSTS=${TS_IP}:3000,${TS_DOMAIN},localhost

  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./uptime-kuma-data:/app/data
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro
    security_opt:
      - label=disable
    logging:
      driver: journald
