services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden_admin_token
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
      - TZ=${TZ}
    secrets:
      - vaultwarden_admin_token
    volumes:
      - ./vaultwarden:/data:Z
    ports:
      - "${VAULTWARDEN_PORT}:80"
    tmpfs:
      - /tmp:size=64M
    logging:
      driver: journald
  radicale:
    image: ghcr.io/kozea/radicale:latest
    container_name: radicale
    restart: unless-stopped
    ports:
      - "${RADICALE_PORT}:5232"
    volumes:
      - ./radicale:/data:Z
      - ./radicale/config:/etc/radicale/config:Z
    command: ["--config", "/data/config"]
    environment:
      - TZ=${TZ}

secrets:
  vaultwarden_admin_token:
    external: true
