server:
    interface: 127.0.0.1
    port: 5053
    do-ip6: no
    do-static-hosts: yes

    # Seguridad básica
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes

forward-zone:
    name: "."
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net
    forward-tls-upstream: yes
